In [1]:
import pickle
import numpy as np

In [3]:
pipe = pickle.load(open('titanic.pkl','rb'))

In [4]:
# Assume user input
test_input2 = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [5]:
pipe.predict(test_input2)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [6]:
#3	female	14.0	1	0	11.2417	C
test_input3 = np.array([3, 'female', 14.0, 1, 0, 11.2417, 'C'],dtype=object).reshape(1,7)


In [7]:
pipe.predict(test_input3)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [8]:
# Assume user input
test_input2 = np.array([1	,"female"	,38.8,	1,	0	,71.2833	,"C"],dtype=object).reshape(1,7)


In [9]:
pipe.predict(test_input2)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [10]:
from flask import Flask, render_template, request, jsonify
import pickle
import numpy as np

app = Flask(__name__)

# Load the model
model = pickle.load(open(r"titanic.pkl", 'rb'))

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    try:
        passenger_class = int(request.form['passs'])
        age = float(request.form['age'])
        gender = str(request.form['gender'])
        sibling_spouse = int(request.form['sibsip'])
        parent_child = int(request.form['parch'])
        fare = float(request.form['fare'])
        embarked = str(request.form['Embarked'])
        
        # Create the feature array
        features = np.array([[passenger_class, gender, age, sibling_spouse, parent_child, fare, embarked]])
        # Make prediction
        preds = model.predict(features)
        
        result = 'Survived' if preds[0] == 1 else 'Not Survived'
        
        return jsonify({"result": result})
    
    except Exception as e:
        return str(e)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8082)


 * Serving Flask app '__main__'
 * Debug mode: off


 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8082
 * Running on http://192.168.1.22:8082
Press CTRL+C to quit
192.168.1.22 - - [15/Nov/2024 10:25:55] "GET / HTTP/1.1" 200 -
192.168.1.22 - - [15/Nov/2024 10:25:56] "GET /favicon.ico HTTP/1.1" 404 -
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
192.168.1.22 - - [15/Nov/2024 10:28:05] "POST /predict HTTP/1.1" 200 -
